spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rydb
    username: jason
    password: 123456

server:
  port: 9091
  servlet:
    context-path: /
mybatis:
  type-aliases-package: com.jason.system.model.domain
  mapper-locations: classpath*:mapper/*Mapper.xml


# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30
