server:
  port: 9091


jwt:
  # ?JWT?????????????????????43
  # ??????????????????????????????????????????
  secret: oQZSeguYloAPAmKwvKqqnifiQatxMEPNOvtwPsCLasd
  # JWT??????????????2?
  expiration: 300000
  header: Authorization
  prefix: hc
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/learndb
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.jason.domain
